# Generated by Django 5.1.4 on 2024-12-17 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("galeria", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fotografia",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("NEBULOSA", "Nebulosa"),
                    ("ESTRELA", "Estrela"),
                    ("GALAXIA", "Galáxia"),
                    ("PLANETA", "Planeta"),
                ],
                default="",
                max_length=100,
            ),
        ),
    ]
