# Generated by Django 5.1.4 on 2024-12-17 18:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("galeria", "0003_fotografia_publicada"),
    ]

    operations = [
        migrations.AddField(
            model_name="fotografia",
            name="data_fatografia",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
