# Generated by Django 5.1.4 on 2024-12-17 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("galeria", "0004_fotografia_data_fatografia"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fotografia",
            old_name="data_fatografia",
            new_name="data_fotografia",
        ),
    ]
